name: Build and Release

on:
  push:
    tags:
      - "v*" # Trigger su tag che iniziano con 'v' (es: v0.1, v1.0)
  workflow_dispatch: # Permette di avviare manualmente

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            output-name: VintedDownloaderGUI-linux
            extension: ""
          - os: windows-latest
            output-name: VintedDownloaderGUI-windows
            extension: ".exe"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build with PyInstaller (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          pyinstaller --onefile --windowed --name=${{ matrix.output-name }} src/gui/vinted_downloader_gui.py

      - name: Build with PyInstaller (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          pyinstaller --onefile --windowed --name=${{ matrix.output-name }} src/gui/vinted_downloader_gui.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.output-name }}
          path: dist/${{ matrix.output-name }}${{ matrix.extension }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
            ## Vinted Downloader GUI ${{ github.ref_name }}

            ### Download per il tuo sistema operativo:
            - **Linux**: `VintedDownloaderGUI-linux`
            - **Windows**: `VintedDownloaderGUI-windows.exe`

            ### Caratteristiche:
            - ✅ Interfaccia grafica intuitiva
            - ✅ Download da Vinted con organizzazione automatica
            - ✅ Gestione coda di download
            - ✅ Progress bar dual per articoli e immagini
            - ✅ Monitoraggio clipboard automatico

            ### Come usare:
            1. Scarica l'eseguibile per il tuo sistema operativo
            2. Rendilo eseguibile (Linux: `chmod +x VintedDownloaderGUI-linux`)
            3. Avvia l'applicazione
            4. Incolla l'URL Vinted e premi Download!
          files: |
            VintedDownloaderGUI-linux/VintedDownloaderGUI-linux
            VintedDownloaderGUI-windows/VintedDownloaderGUI-windows.exe
